- hosts: localhost
  vars:
    ros2_gpg_key_url: "https://raw.githubusercontent.com/ros/rosdistro/master/ros.key"
    ros2_repository_url: "http://packages.ros.org/ros2/ubuntu"
    # Options: bouncy; crystal; dashing (LTS); eloquent; foxy (LTS)
    ros2_distribution: foxy
    # Options: desktop (recommended); ros-base (bare bones)
    ros2_configuration: desktop

  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      upgrade: yes
      force_apt_get: true
      update_cache: true
      cache_valid_time: 86400 #One day
      state: present
    tags:
      - setup

  tasks:
    - include: tasks/ros2-install.yml
