- name: Install dependencies for setting up sources
  become: yes
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - curl
    - gnupg2
    - lsb-release
    - software-properties-common

- name: Check if the universe repository is already configured
  shell: "grep -R '^deb .*universe' /etc/apt/sources.list /etc/apt/sources.list.d/"
  register: universe_repo_check
  ignore_errors: yes
  changed_when: false  # Prevents marking this task as "changed" if no match is found

- name: Enable ubuntu universe repository
  become: yes
  shell: "add-apt-repository universe -y"
  when: universe_repo_check.rc != 0  # Only add if the grep command didn't find any matching repo

- name: Update Apt
  become: true
  apt:
    upgrade: yes
    force_apt_get: true
    update_cache: true
    state: present

# sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
- name: Setup ROS2 keys
  become: yes
  ansible.builtin.get_url:
    url: "{{ ros2_gpg_key_url }}"
    dest: /usr/share/keyrings/ros-archive-keyring.gpg

# echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
- name: Setup ROS2 sources
  become: yes
  apt_repository:
    repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] {{ ros2_repository_url }} {{ ansible_distribution_release }} main"
    state: present
    filename: ros2

# sudo apt install ros-<distro>-ros-desktop
- name: Install ROS2
  become: yes
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - "{{ 'ros-' + ros2_distribution + '-' + ros2_configuration }}"

# sudo apt install python3-argcomplete
- name: Install argcomplete (optional)
  become: yes
  apt:
    name: python3-argcomplete

- name: Install colcon to build packages
  become: yes
  apt:
    name: python3-colcon-common-extensions

- name: Install ROS Dev Tools (only for jazzy)
  become: yes
  apt:
    name: ros-dev-tools
    state: present
  when: ros2_distribution == "jazzy"

- name: Install Default Gazebo/ROS Pairing
  become: yes
  apt:
    name: ros-jazzy-ros-gz
    state: present
  when: ros2_distribution == "jazzy"
